=========================================================================================== 
Warning! Due to the issue with the current installation of setuptools_scm in
the 2023 software 
environment, we need to rebuild the following packages:
  hatchling, Python-bundle-PyPI, and Python

The rebuild is scheduled for Thursday 23.05.2024 at 09:00 and will last for
approx. 30 minutes. During 
this period, the above mentioned packages will be unavailable. You can read
more about the issue 
following this link:
https://github.com/easybuilders/easybuild-easyconfigs/issues/19849 
We are sorry for any inconvenience.

In case of any questions, please reach us out by submitting a ServiceDesk
ticket: 
https://servicedesk.surf.nl
============================================================================================== 
Traceback (most recent call last):
  File "/gpfs/home5/scur1193/DL2/DL2-group5-med-seg/src/download_dataset.py", line 4, in <module>
    dataset = load_dataset("GoodBaiBai88/M3D-Seg", cache_dir=os.environ["TMPDIR"])
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 2259, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 1904, in dataset_module_factory
    raise e1 from None
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 1892, in dataset_module_factory
    ).get_module()
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 1270, in get_module
    module_name, default_builder_kwargs = infer_module_for_data_files(
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 597, in infer_module_for_data_files
    raise DataFilesNotFoundError("No (supported) data files found" + (f" in {path}" if path else ""))
datasets.exceptions.DataFilesNotFoundError: No (supported) data files found in GoodBaiBai88/M3D-Seg

JOB STATISTICS
==============
Job ID: 6281546
Cluster: snellius
User/Group: scur1193/scur1193
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:23
CPU Efficiency: 2.84% of 00:13:30 core-walltime
Job Wall-clock time: 00:00:45
Memory Utilized: 128.00 MB
Memory Efficiency: 0.10% of 120.00 GB
Traceback (most recent call last):
  File "/gpfs/home5/scur1193/DL2/DL2-group5-med-seg/src/download_dataset.py", line 4, in <module>
    dataset = load_dataset("GoodBaiBai88/M3D-Seg", cache_dir=os.environ["TMPDIR"])
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 2259, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 1904, in dataset_module_factory
    raise e1 from None
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 1892, in dataset_module_factory
    ).get_module()
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 1270, in get_module
    module_name, default_builder_kwargs = infer_module_for_data_files(
  File "/home/scur1193/.local/lib/python3.10/site-packages/datasets/load.py", line 597, in infer_module_for_data_files
    raise DataFilesNotFoundError("No (supported) data files found" + (f" in {path}" if path else ""))
datasets.exceptions.DataFilesNotFoundError: No (supported) data files found in GoodBaiBai88/M3D-Seg

JOB STATISTICS
==============
Job ID: 6281548
Cluster: snellius
User/Group: scur1193/scur1193
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:00:23
CPU Efficiency: 3.12% of 00:12:18 core-walltime
Job Wall-clock time: 00:00:41
Memory Utilized: 1.12 MB
Memory Efficiency: 0.00% of 120.00 GB
